version: '3.9'

services:
  postgres:
    image: postgres:17.0-alpine
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}